[workspace]
resolver = "3"
members = [
    "share-lib",
    "watchman-backend",
    "cmdb-backend",
    "cloud-api",
    "file-agent",
    "jc-commander",
    "jc-worker",
    "yell",
]

[workspace.package]
version = "0.1.0"
edition = "2024"
authors = ["Cdog Shen <shencdog@outlook.com>"]

[workspace.dependencies]
# share-lib utils
share-lib = { path = "./share-lib" }

# std dependencies
once_cell = "1.21.4"
log = "0.4.34"
chrono = { version = "0.4.45", features = ["serde"] }
tokio = "1.53.1"
futures = "0.3.34"
crossbeam = "0.8.4"
# basic web dependencies
actix-web = "4.15.0"
actix-rt = "2.13.0"
actix-service = "2.0.3"
actix-cors = "0.7.2"
actix-multipart = "0.8.1"
# DB dependencies
diesel_migrations = "2.3.2"
diesel = { version = "2.3.12", features = [
    "postgres",
    "r2d2",
    "chrono",
    "serde_json",
    "uuid",
] }
pq-sys = { version = "0.7.5", features = ["bundled_without_openssl"] }
# serialization dependencies
serde = "1.0.229"
serde_derive = "1.0.229"
serde_json = "1.0.151"
uuid = { version = "1.26.0", features = ["v4", "serde"] }
# RPC dependencies
ureq = { version = "3.4.0", features = ["charset", "json"] }
# MQ dependencies
lapin = "4.10.0"
# auth dependencies
jsonwebtoken = "11.0.0"
bcrypt = "0.19.3"
base64 = "0.23.1"
# async dependencies
async-trait = "0.1.92"
# email dependencies
lettre = { version = "0.11.23", features = [
    "tokio1",
    "tokio1-native-tls",
    "builder",
] }
# misc dependencies
sanitize-filename = "0.6.0"
toml = "1.1.4+spec-1.1.0"
