[package]
name = "jc-worker"
version = "0.1.0"
edition = "2024"

[dependencies]
# std dependencies
once_cell = "1.21.4"
log = "0.4.29"
chrono = { version = "0.4.44", features = ["serde"] }
futures = "0.3.32"
tokio = { version = "1.47.1", features = ["full"] }
# toml = "0.8.19"
# DB dependencies
# diesel_migrations = "2.2.0"
# diesel = { version = "2.2.8", features = ["mysql", "r2d2", "chrono"] }
# serializtion dependencies
serde = "1.0.228"
serde_derive = "1.0.228"
serde_json = "1.0.149"
uuid = { version = "1.23.1", features = ["v4"] }
# RPC dependencies
ureq = "3.3.0"
# MQ dependencies
lapin = "3.2.1" 
# share-lib utils
share-lib = { path = "../share-lib" }
