[package]
name = "cloud-api"
version.workspace = true
edition.workspace = true

[dependencies]
# std dependencies
once_cell.workspace = true
log.workspace = true
chrono.workspace = true
# basic web dependencies
actix-web.workspace = true
actix-rt.workspace = true
actix-service.workspace = true
actix-cors.workspace = true
futures.workspace = true
# DB dependencies
diesel_migrations.workspace = true
diesel.workspace = true
pq-sys.workspace = true
# serialization dependencies
serde.workspace = true
serde_derive.workspace = true
serde_json.workspace = true
uuid.workspace = true
# RPC dependencies
ureq.workspace = true
# share-lib utils
share-lib = { workspace = true, features = ["web"] }
