[server_config]
log_path = "logs/cmdb.log"
log_level = "INFO"
clear_log = "True"
listen_addr = "127.0.0.1"
listen_port = 9001
workers = 2
uuid = "xxx"
master_addr = "127.0.0.1"
master_port = 8000
register_name = "cmdb"
allowed_origin_list = ["http://localhost:3000", "http://127.0.0.1:3000"]
authenticate_bypass = ["/api/refresh_master"]

[db_config]
db_str = "mysql://root:778631@127.0.0.1:3306/cmdb"