### vars
@baseurl = http://127.0.0.1:8000/api
@token = bearer 

### all_subsystem
GET {{baseurl}}/subsystem_control/all_subsystem HTTP/1.1

### reload config
POST {{baseurl}}/subsystem_control/new_subsystem HTTP/1.1
Authorization: {{token}}
Content-Type: application/json

{
    "subsys_name": "subsys1",
    "url": "http://127.0.0.1:8000/api",
    "is_enable": 1,
    "relate_service": null,
    "token": ""
}

### call cloud API
POST {{baseurl}}/subsystem_call/cloud_api HTTP/1.1
Authorization: {{token}}
Content-Type: application/json

{
    "target": "script",
    "operation": "call",
    "data": {
        "api_name": "tencent_cvm_describeinstances",
        "cloud_user": "Unknow-api-xx",
        "region": "ap-shanghai",
        "params": "{\"Offset\": 1, \"Limit\": 20}"
    }
}

### call jc
POST {{baseurl}}/subsystem_call/jc_commander_1 HTTP/1.1
Authorization: {{token}}
Content-Type: application/json

{
    "target": "script",
    "operation": "async",
    "data": {
        "script": "business_TxCvmUpdate",
        "host": "any",
        "params": {}
    }
}

###