### vars
@baseurl = http://localhost:8000/api/subsystem
@token = bearer xxx


### all subsystem
GET {{baseurl}} HTTP/1.1
Authorization: {{token}}
Content-Type: application/json

### new subsystem
POST {{baseurl}} HTTP/1.1
Authorization: {{token}}
Content-Type: application/json

{
    "subsys_name": "test",
    "url": "http://localhost:8000/api/hey",
    "is_enable": true,
    "relate_service_id": 0,
    "token": "ea1ec535-3f77-4df3-9e67-918df7e2f923"
}

### update subsystem
PATCH {{baseurl}} HTTP/1.1
Authorization: {{token}}
Content-Type: application/json

{
    "id": 4,
    "relate_service_id": 0
    # "is_enable": false
}

### delete subsystem
DELETE {{baseurl}} HTTP/1.1
Authorization: {{token}}
Content-Type: application/json

{
    "id": 3
}
