[package]
name = "share-lib"
version = "0.1.0"
edition = "2021"
authors = ["Cdog Shen <shencdog@oulook.com>"]

[dependencies]
serde = { version = "1.0.215", features = ["derive"] }
toml = "0.8.19"
time = { version = "0.3.36", features = ["serde", "formatting"] }
log = { version = "0.4", features = ["std"] }
once_cell = "1.20.2"
