[package]
name = "share-lib"
version.workspace = true
edition.workspace = true
authors.workspace = true

[features]
default = []
web = ["dep:actix-web"]

[dependencies]
serde = { workspace = true, features = ["derive"] }
serde_derive.workspace = true
serde_json.workspace = true
chrono.workspace = true
log = { workspace = true, features = ["std"] }
toml.workspace = true
actix-web = { workspace = true, optional = true }
